version: '3'

services:
  app:
    build: .
    depends_on:
      - pg
      - redis
    env_file:
      - .env
    build: .
    ports:
      - 3000:3000

  sidekiq:
    build: .
    depends_on:
      - pg
      - redis
    env_file:
      - .env
    command: sidekiq
    volumes:
      - /tmp:/storage

  discord_listener:
    build: .
    depends_on:
      - pg
      - redis
    env_file:
      - .env
    command: bin/discord_listener

  pg:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  redis:
    image: redis:6.0.10-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
