default: &default
  adapter: postgresql
  username: postgres
  password: postgres
  host: <%= ENV['IN_DOCKER'] ? 'pg' : 'localhost' %>
  port: 5432
  encoding: unicode

development:
  <<: *default
  database: kudochest_dev
  min_messages: warning

test:
  <<: *default
  database: kudochest_test
  min_messages: error
  variables:
    statement_timeout: 90s

production_default: &production_default
  <<: *default
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

production:
  primary:
    <<: *production_default
    host: <%= ENV['DB_HOST_WRITER'] %>
  primary_replica:
    <<: *production_default
    host: <%= ENV['DB_HOST_READER'] %>
    replica: true
