hints:
  - 'Give kudos to everyone in the current channel by saying `@channel++`'
  - 'Give kudos to everyone in a channel by saying `#some-channel++`'
  - '"Be excellent to each other" - The Wild Stallions'
