:max_retries: 5

:scheduler:
  HourlyTeamWorker:
    cron: '0 0 * * * * America/Los_Angeles' # Hourly

  WeeklyReport::RecurrentWorker:
    cron: '0 0 8 * * 1 America/Los_Angeles' # Every Monday at 8am
